test push

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,18 +1,21 @@
 #!/bin/sh
+
 . "$(dirname "$0")/_/husky.sh"
 
-echo "🔍 Running ESLint..."
+set +e
+
+echo "Running ESLint..."
 npm run lint
 LINT_STATUS=$?
 
-# Check if ggshield is installed
-if ! command -v ggshield >/dev/null 2>&1; then
-  echo "❌ ggshield not found"
-  echo "👉 Install it using: pipx install ggshield"
+# Check if trufflehog is installed
+if ! command -v trufflehog >/dev/null 2>&1; then
+  echo  trufflehog not found"
+  echo " Install it using: apt install trufflehog"
   GG_STATUS=1
 else
-  echo "🔐 Running GGShield secret scan..."
-  ggshield secret scan pre-commit
+  echo "🔐 Running trufflehog secret scan..."
+trufflehog git file://. --since-commit HEAD --only-verified --fail
   GG_STATUS=$?
 fi
 
@@ -25,9 +28,9 @@ else
 fi
 
 if [ $GG_STATUS -ne 0 ]; then
-  echo "❌ GGShield secret scan failed"
+  echo "❌ trufflehog secret scan failed"
 else
-  echo "✅ GGShield secret scan passed"
+  echo "✅ trufflehog secret scan passed"
 fi
 
 echo "----------------------------"
